- pom.xml
- src/main/java/com/patina/codebloom/GlobalExceptionHandler.java
- src/main/java/com/patina/codebloom/api/ApiController.java
- src/main/java/com/patina/codebloom/api/auth/AuthController.java
- src/main/java/com/patina/codebloom/api/auth/CustomOpenApiAuthItems.java
- src/main/java/com/patina/codebloom/api/test/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/dto/ApiResponder.java
- src/main/java/com/patina/codebloom/common/dto/autogen/__DO_NOT_USE_UNLESS_YOU_KNOW_WHAT_YOU_ARE_DOING_GENERIC_FAILURE_RESPONSE.java
- src/main/java/com/patina/codebloom/common/metadata/ServerMetadataObject.java
- src/main/java/com/patina/codebloom/common/openapi/OpenApiConfig.java
- src/main/resources/application.properties
-  Implemented Springdoc to handle API documentation. 
-  Renamed ApiResponse to ApiResponder to avoid namespace collision with swagger's ApiResponse. 
- Added some custom API documentation for the OAuth routes that are abstracted off by Spring-Security.
Developers must add 
```env
ENABLE_DOCUMENTATION=true
```
to their `.env` files in order to enable the Swagger and OpenAPI endpoints. Once enabled (along with the development server running), developers may go to `/swagger-ui.html` to view the endpoint documentation.
> Add API Documentation

- db/migration/V21__Drop_question_slug_unqiue.SQL
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- src/main/java/com/patina/codebloom/common/submissions/SubmissionsHandler.java
Codebloom can now support multiple submissions from any previous question, albeit with the points being set to a default of 0. In the future, when we implement filters, these questions will be hidden by default and can be toggled back on.
> Allow duplicate submissions

- .lazy.lua
- .nvim.lua
- checkstyle.xml
- java-formatter.xml
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
The biggest problem with the old .nvim.lua file is that it does not work for lazy.nvim plugins whatsoever. It was essentially a race condition hack that would fail half of the time. However, this should no longer be an issue as the .lazy.lua file will override any plugins that have been set inside of the base neovim config. This will now properly apply the proper plugin overrides required to use Checkstyle and Java formatter within Neovim. .nvim.lua still enforces the tab size to be 4 spaces. Improved Checkstyle and Java Formatter config files to be more consistent.
> Update Neovim config & make Checkstyle and Java Formatter be consistent.

- js/src/app/submission/u/[userId]/hooks.ts
- js/src/lib/hooks/useUrlState.ts
Implemented an extra debounce value within useUrlState in order to support more expensive calculations such as search querying. The debounced value and the regular value are decoupled as the developer may still want to control a text input, of which the debounced value would be unusable for.
> Support debounce for useUrlState + implemented debounce for submission search (DESC)

- js/src/app/dashboard/_components/RecentSubmissions/RecentSubmissions.tsx
- js/src/lib/api/queries/user/index.ts
Changed logic to hard fetch 20 questions, but we only use the first 5 for the dashboard page. Now we don't have to keep refetching data btwn the dashboard and viewing all submissions
> Fixed bug on submission user fetch query

- src/main/resources/application.properties
This will stop the bug where the logo image is changed every single time on the frontend. The TTL is set relatively low at 30m so that if we decide to change the image or logo, it will expire relatively soon. This won't affect .js,.css,.html or any other files from Vite because those files have hashes and change everytime we re-deploy.
> Enabled asset caching on the server (DESC)

- js/src/lib/api/queries/leaderboard/index.ts
- js/src/lib/hooks/useUrlState.ts
The problem was that the useEffect to reset the page to page 1 when patina or query changes would cause the page state to break because it would be toggled back to page 1 before the state would finish running. The better solution would be to reset the page whenever the actual functions to update the patina filter or updagte query actually runs, which will only run when invoked, not on render.
> Fix useUrlState bug with page in leaderboard query (DESC)

- js/src/app/_component/AboutUs.tsx
- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
- js/src/app/_component/skeletons/MiniLeaderboardMobileSkeleton.tsx
- js/src/app/_component/skeletons/MiniLeaderboardSkeleton.tsx
- js/src/app/leaderboard/Leaderboard.page.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/app/leaderboard/_components/LeaderboardSkeleton.tsx
The problem with the leaderboard items is that the entire list loads, and then when the list is loaded, it then queries to load the metadata. Here is an example:
```tsx
export default function leaderboardList() {
// Example query
const { data, status } = fetchLeaderboardListQuery();
if (status === "pending") {
return <Loader />;
}
if (status === "error") {
return <div>Sorry, something went wrong.</div>;
}
const { data: listData } = data;
return (
<div className="flex flex-row justify-center gap-4">
{/* This metadata will not start loading until we finish loading the list. */}
<LeaderboardMetadata />
{listData.map((player) => (
<div>
<div>{player.name}</div>
...
</div>
))}
</div>
);
}
```
This should be resolved now, and the skeletons should reflect these changes.
> Fix waterfalls

- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
- js/src/app/admin/_components/UserAdminList.tsx
- js/src/app/dashboard/_components/DashboardLeaderboard/DashboardLeaderboard.tsx
- js/src/app/dashboard/_components/RecentSubmissions/RecentSubmissions.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/app/user/[userId]/_components/UserSubmissions/UserSubmissions.tsx
- js/src/lib/api/common/page.ts
- js/src/lib/api/queries/admin/index.ts
- src/main/java/com/patina/codebloom/common/page/Page.java
This is similar to this PR #175: **Update the ApiResponder object in the backend to use payload instead of data**
The `data` attribute on the `Page` DTO was too confusing when chained with React Query and `ApiResponder`(backend)/`ApiResponse`(client). So, as a result, it has now been renamed to `items` to increase the clarity of what the utility of the method is.
> Update the Page object in the backend to use items instead of data.

- js/src/lib/api/common/apiResponse.ts
- js/src/lib/api/queries/admin/index.ts
- js/src/lib/api/queries/auth/index.ts
- js/src/lib/api/queries/auth/leetcode/index.ts
- js/src/lib/api/queries/leaderboard/index.ts
- js/src/lib/api/queries/potd/index.ts
- js/src/lib/api/queries/submissions/index.ts
- js/src/lib/api/queries/user/index.ts
- js/src/lib/prettify/index.ts
- Renamed `ApiResponse` to `UnknownApiResponse` to improve clarity about whether or not the `payload` attribute is available
- Renamed the success and error types to be a little less vague. The intent is so that if anyone were to read the source code, it would be a little easier to understand the purpose of each type.
- Wrapped the success and error types in Prettify so that their types are more opaque when read, for example, via a hover in VSCode.
- Added some examples and documentation on `UnknownApiResponse`.
> Modified ApiResponse object

- js/src/lib/api/queries/admin/index.ts
Fixed the issues where the optimistic queries were using the older .data/.data.data methods from UnknownApiResponse & Page types. However, this issue only existed because of the fact that type assertion was being used where we should have used type annotation, which led to TS blindly trusting us with the type of the data. As such, those type assertions were removed and replaced with assertions instead.
> Fixed the optimistic updates in the admin list (DESC)

- .env.example
- src/main/java/com/patina/codebloom/jda/JDAProperties.java
- src/main/java/com/patina/codebloom/jda/client/JDAClient.java
- src/main/java/com/patina/codebloom/scheduled/discord/WeeklyLeaderboard.java
- src/main/resources/application.properties
Implement JDAClient to interface with JDA logic instead of directly interfacing with JDA. Added some helper functions, including the ability to send a Patina leaderboard message to a channel and guild. In the future, this logic can be trivially modified to report school specific leaderboards to their respective Discord servers as well.
> Implement JDAClient + Add weekly Discord leaderboard message 

- db/repeated/R__Mock_v2.SQL
- pom.xml
- src/main/java/com/patina/codebloom/common/db/models/user/User.java
- src/main/java/com/patina/codebloom/common/dto/ApiResponder.java
- src/test/java/com/patina/codebloom/ApiControllerTest.java
- src/test/java/com/patina/codebloom/admin/AdminControllerTest.java
- src/test/java/com/patina/codebloom/leetcode/LeetcodeApiHandlerTest.java
- src/test/java/com/patina/codebloom/leetcode/ScoreCalculatorTest.java
- src/test/java/com/patina/codebloom/testconfig/TestProtector.java
- Added some missing RestAssured dependencies
- Implement a TestProtector that uses a user that exists in all dev/CI dbs that has admin access, allowing us to test authenticated endpoints
- Implement a test for AdminController toggling user's admin status
- Implement a test for base ApiController returning the ServerMetadataObject
> Implement some testing configs + add some example tests

- Makefile
- docs/backend/automatic-type-gen.md
- docs/frontend/automatic-type-gen.md
- src/main/java/com/patina/codebloom/utilities/JSTypesGenerator.java
Fix the openapi-typescript generation loop by moving it out of the Makefile and instead registering the command under a command line runner & component inside of the actual Java process (only in dev)
> Fix openapi-typescript infinite loop (DESC)

- src/main/java/com/patina/codebloom/api/auth/AuthController.java
-returns newRedirectView
-wrapped  the protector.validateRequest logic in a try catch to stop the regular exception from being thrown. If an exception is thrown here, send to /login instead of /settings.
> Update the JWT callback to use RedirectView

- js/src/app/settings/_components/SchoolEmailModal.tsx
- js/src/lib/api/queries/auth/school/index.ts
Even though invalidateQueries is an async function, it is blocking the execution of the `mutate()` hook level `onSuccess`, which is blocking the notification message update to show the response from the server. An acceptable hack is to wrap invalidateQueries in a setTimeout, and defer it's execution via a callback 100ms from the register point.
> School modal hack

- js/src/components/ui/header/Header.tsx
- src/main/java/com/patina/codebloom/common/db/models/user/PrivateUser.java
- src/main/java/com/patina/codebloom/common/db/models/user/User.java
new type signature of `User`:
new type signature of `PrivateUser`:
the database schema type of `User` from Dbeaver showing that `schoolEmail` can be `null` and `profileUrl` can be `null`:
> Fix the type of profileUrl & schoolEmail to indicate that it can be null

- db/repeated/R__Mock_v10.SQL
- src/main/java/com/patina/codebloom/api/admin/AdminController.java
- src/main/java/com/patina/codebloom/api/admin/body/DeleteAnnouncementBody.java
-added a repeated db migration for announcement for testing purposes
-added delete Body 
- wrote endpoint using remove announcement logic 
**DB Migration** 
**Announcement response after testing** 
**Database after deleting and front end**
> Remove announcement logic

- src/main/java/com/patina/codebloom/api/auth/security/CustomAuthenticationSuccessHandler.java
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/leetcode/LeetcodeClientImpl.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/GetPotd.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/GetSubmissionDetails.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/GetUserProfile.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/SelectAcceptedSubmisisonsQuery.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/SelectProblemQuery.java
- src/main/java/com/patina/codebloom/common/leetcode/throttled/ThrottledLeetcodeClient.java
- src/main/java/com/patina/codebloom/common/leetcode/throttled/ThrottledLeetcodeClientImpl.java
- src/main/java/com/patina/codebloom/common/submissions/SubmissionsHandler.java
- src/main/java/com/patina/codebloom/scheduled/leetcode/RefetchIncompleteQuestions.java
- src/main/java/com/patina/codebloom/scheduled/potd/PotdSetter.java
- src/main/java/com/patina/codebloom/scheduled/submission/SubmissionScheduler.java
- src/test/java/com/patina/codebloom/leetcode/LeetcodeClientTest.java
- Refactored LeetcodeClient to re-use one HttpClient as it is thread-safe and is able to maintain a pool of requests. 
- Refactored building the body of each request into the actual query classes so it's easier to keep track of what body is owned by what query. 
- Refactored the request builder into a private function called  which will apply defaults to each HttpRequest. 
- Created ThrottledLeetcodeClient which will force all requests to be maxed out at 35 req/s. This new class has replaced every place that is using LeetcodeClientImpl. 
- Added a new test to LeetcodeClientTest which will attempt to stress test the client by making 100 threads * 50 requests per thread = 5,000 requests, which should give us adequate breathing room without hitting any limits.
> Update leetcode client + add throttled leetcode client (desc)

- src/test/java/com/patina/codebloom/leetcode/LeetcodeClientTest.java
Tests keep failing due to 1-11 failures. 4500 total requests should stop tests from failing, and still be well over what the regular `LeetcodeClient` can support
> Changed requests per thread to 45 from 50

- src/main/java/com/patina/codebloom/api/admin/AdminController.java
- src/main/java/com/patina/codebloom/common/db/models/announcement/Announcement.java
- src/main/java/com/patina/codebloom/common/db/repos/announcement/AnnouncementRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/announcement/AnnouncementSqlRepository.java
- src/test/java/com/patina/codebloom/db/announcement/AnnouncementRepositoryTest.java
-added update announcement in announcement sql repo and repo
- added update announcement test and fixed logic of other test functions
- added new logic for admin controller 
- addes setter to all announcements
**Before**
**RESPONSE from Admin Controller**
**DB AFTER**
> Update announcement delete to use updateAnnouncement

- infra/copy-prod-db.sh
the script drops:
- `AuthKey`,
-  `Auth`,
-  `Club`,
-  `Session`. 
it also modifies all rows inside of `User` that are have `admin = false` and scrubs:
- `nickname`,
-  `verifyKey`,
-  `schoolEmail`
-  `profileUrl`. 
I chose not to scrub `discordId`, `discordName`, or `leetcodeUsername` because they aren't considered sensitive or private anyways. 
Testing:
Copied production data to a local database instance, and attempting to copy it to another local database instance (that was empty).
.env
```
DATABASE_HOST=localhost
DATABASE_PORT=5432
PRODUCTION_DATABASE_NAME=codebloom-prod-copy-sep-20
STAGING_DATABASE_NAME=codebloom-stg-2
DATABASE_USER=postgres
DATABASE_PASSWORD=passwordnomas
```
command:
```
dotenvx run -f infra/.env -- ./infra/copy-prod-db.sh
```
output: …
> Add script to copy data from production db to staging db and scrub/drop any sensitive information
