- js/src/app/login/Login.page.tsx
- js/src/app/login/hooks.ts
- js/src/components/ui/toast/Toast.tsx
- js/src/components/ui/toast/ToastWithRedirect.tsx
- js/src/main.tsx
- Created new components to help compose better logic for redirects and toast popups. 
- Added a custom hook to read any queries attached to /login that would be returned from the backend.
- Imported Mantine Notification CSS file, which was not previously imported.
> Updated authentication logic on frontend

- js/src/main.tsx
Force dark mode on the frontend in order to be inline with Patina's main website.
> Force dark mode on frontend

- js/package.json
- js/src/app/dashboard/Dashboard.page.tsx
- js/src/components/ui/LogoutButton.tsx
- js/src/lib/router.tsx
- Dashboard.page.tsx: If user is authenticated, then user is redirected to /api/auth/logout. If not, then user is redirected to /login"
- LogoutButton.tsx: Logout button declared with link to /api/auth/logout
- Router.tsx: Added path to /dashboard
> Set up the logout button with authentication

- js/src/app/login/Login.page.tsx
- js/src/components/ui/auth/LoginButton.tsx
- LoginButton.tsx: added radius to the button 
- Login.page.tsx: created a stack with big card to the log in button and smaller card underneath to go back to /; each page is centered with appropriate text, font, and width size
> Button reorganization

- src/main/java/com/patina/codebloom/GlobalExceptionHandler.java
- src/main/java/com/patina/codebloom/api/auth/security/CustomAuthenticationSuccessHandler.java
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/api/submission/body/LeetcodeUsernameObject.java
- src/main/java/com/patina/codebloom/common/db/models/question/Question.java
- src/main/java/com/patina/codebloom/common/db/models/question/QuestionDifficulty.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
- src/main/java/com/patina/codebloom/common/kv/KeyValueStore.java
- src/main/java/com/patina/codebloom/common/leetcode/DefaultLeetcodeApiHandler.java
- src/main/java/com/patina/codebloom/common/leetcode/models/LeetcodeQuestion.java
- src/main/java/com/patina/codebloom/common/leetcode/score/ScoreCalculator.java
- src/main/java/com/patina/codebloom/common/submissions/SubmissionsHandler.java
- src/main/java/com/patina/codebloom/common/submissions/object/AcceptedSubmissions.java
- src/main/resources/db/migration/V12__Set_question_slug_to_unique.SQL
- src/main/resources/db/migration/V13__Add_acceptance_rate_to_question_table.SQL
- Updated method on UserRepository from updateUserById to updateUser to improve input ambiguity.
- Required questionSlug in Question table unique per user and added acceptanceRate to Question table.
- Implemented a SubmissionsHandler that does the comparison logic between Leetcode and our database and awards points as necessary.
- Implemented a basic points system that utilizes difficulty and acceptance rate, as well as applying a basic deviation of 5%.
- Implemented a basic in-memory key value store that is used to rate-limit the submissions check API to prevent abuse.
> Submission API

- js/package.json
- js/pnpm-lock.yaml
- js/src/app/dashboard/components/OnboardingLeetcodeUser.tsx
- js/src/app/dashboard/components/RefreshSubmissions.tsx
- js/src/app/dashboard/hooks.ts
- js/src/app/onboarding/Onboarding.page.tsx
- js/src/app/onboarding/components/UsernameForm.tsx
- js/src/app/onboarding/hooks.ts
- js/src/components/ui/header/Header.tsx
- js/src/lib/router.tsx
- js/src/lib/types/db/user.ts
- src/main/java/com/patina/codebloom/CodebloomApplication.java
- src/main/java/com/patina/codebloom/GlobalExceptionHandler.java
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/dto/ApiResponder.java
- src/main/java/com/patina/codebloom/common/dto/autogen/__DO_NOT_USE_UNLESS_YOU_KNOW_WHAT_YOU_ARE_DOING_RATE_LIMIT_FAILURE_RESPONSE.java
-GlobalExceptionHandler.java has some error in line 31 that doesn't allow mvn clean install to run
> Added form for point submission and username check

- src/main/java/com/patina/codebloom/CodebloomApplication.java
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/api/test/leaderboard/TestLeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
- src/main/java/com/patina/codebloom/common/leetcode/DefaultLeetcodeApiHandler.java
- src/main/java/com/patina/codebloom/scheduled/submission/SubmissionScheduler.java
- Implemented the scheduled task of checking every user's leetcode username with a current repetition of every 30 minutes [Value WIP].
- Removed some extra imports and unused variables.
> Submission Scheduler

- js/src/app/component/AboutUs.tsx
- js/src/app/component/MiniLeaderboardMobile.tsx
- js/src/app/dashboard/components/LeaderboardForDashboard/LeaderboardForDashboard.tsx
- js/src/app/dashboard/components/ProblemOfTheDay/ProblemOfTheDay.tsx
- js/src/app/dashboard/components/ProblemOfTheDay/hooks.ts
- js/src/app/dashboard/components/RecentSubmissions/RecentSubmissions.tsx
- js/src/app/dashboard/components/RefreshSubmissions.tsx
- js/src/app/dashboard/hooks.ts
- js/src/components/ui/header/Header.tsx
- js/src/lib/types/db/potd.ts
- src/main/java/com/patina/codebloom/FakeLag.java
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/db/repos/potd/POTDSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- src/main/java/com/patina/codebloom/common/dto/ApiResponder.java
- src/main/java/com/patina/codebloom/common/leetcode/score/ScoreCalculator.java
- src/main/java/com/patina/codebloom/common/submissions/SubmissionsHandler.java
- src/main/resources/db/migration/V15__Create_POTD_table.SQL
- Implemented the problem of the day from the backend to the frontend.
- Implemented a slowdown to improve UX as well as catch and fix poor loading indicatiors [in the future, the loading indicators will be replaced with skeletons]. 
- Fixed some inconsistensies with POTDRepository and QuestionRepository.
> Implemented the problem of the day from the backend to the frontend. 

- js/src/app/submission/u/[userId]/components/CustomPagination.tsx
- js/src/app/submission/u/[userId]/components/UserSubmissionContent.tsx
- js/src/app/submission/u/[userId]/hooks.ts
- js/src/lib/custom-hooks/use-url-state.ts
- Authored useURLState, which is a custom useState that connects the lifecycle of the URL search params with the function's state. Replaced LoadingOpacity with Opacity to match standard website conventions (websites such as leetcode.com do it this way.)
- Update custom pagination jumpto text & improved UI/UX on the actual paginated submission table.
> Fixing pagination

- db/migration/V19__Enable_pgcrypto_extension.SQL
- db/migration/V20__Add_verify_key_to_user_table.SQL
- js/src/app/_component/OurFeatures.tsx
- js/src/app/onboarding/_components/UsernameForm.tsx
- js/src/app/onboarding/hooks.ts
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/db/models/user/PrivateUser.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
- src/main/java/com/patina/codebloom/common/leetcode/DefaultLeetcodeApiHandler.java
- src/main/java/com/patina/codebloom/common/leetcode/LeetcodeApiHandler.java
- src/main/java/com/patina/codebloom/common/leetcode/models/UserProfile.java
- src/main/java/com/patina/codebloom/common/leetcode/queries/GetUserProfile.java
- src/main/java/com/patina/codebloom/utilities/GlobalExceptionHandler.java
Implemented a column in the User table called veriifyKey that must be set in the logged-in user's Leetcode profile (in the Summary section) in order to claim a username. This should protect abuse and unauthorized theft of usernames
> Implemented a verification method for onboarding

- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- Added string query on QuestionSqlRepository and SQL to search for question title 
- Implemented the logic for accepting the string query in the controller
> Implement backend for search on submissions page

- js/.prettierrc
- js/package.json
- js/pnpm-lock.yaml
- js/src/app/submission/u/[userId]/_components/SearchBox.tsx
- js/src/app/submission/u/[userId]/_components/UserSubmissionContent.tsx
- js/src/app/submission/u/[userId]/hooks.ts
Implemented the newly added search query for the submissions API to the frontend
> Search bar for Submissions page

- js/src/app/dashboard/_components/RecentSubmissions/RecentSubmissions.tsx
- js/src/app/submission/u/[userId]/_components/UserSubmissionContent.tsx
- js/src/app/submission/u/[userId]/hooks.ts
- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/question/QuestionSqlRepository.java
- src/main/java/com/patina/codebloom/utilities/GlobalExceptionHandler.java
Remodeled the shape of the user's submissions to be easier accessible, which allows us to fix some bugs where a search query with 0 results would instead throw up a page wide error instead of throwing the error within the table.
> Remodeled user submissions data shape (DESC)

- src/main/java/com/patina/codebloom/api/submission/SubmissionController.java
- added a description and example for query parameter
> Added documentation for query parameter

- db/migration/V23__Create_user_tags_table.SQL
- src/main/java/com/patina/codebloom/api/auth/security/CustomAuthenticationSuccessHandler.java
- src/main/java/com/patina/codebloom/api/test/leaderboard/helper/TestLeaderboardList.java
- src/main/java/com/patina/codebloom/common/db/models/user/PrivateUser.java
- src/main/java/com/patina/codebloom/common/db/models/user/User.java
- src/main/java/com/patina/codebloom/common/db/models/user/UserWithQuestions.java
- src/main/java/com/patina/codebloom/common/db/models/user/UserWithScore.java
- src/main/java/com/patina/codebloom/common/db/models/usertag/Tag.java
- src/main/java/com/patina/codebloom/common/db/models/usertag/UserTag.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/usertag/UserTagRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/usertag/UserTagSqlRepository.java
Implemented User Tags which is a table that is derived from the User table. All User Tags are automatically jointed to the User models from the SQL repositories, but in order to update User Tags, you have to use the UserTagRepository. These tags will allow us to mark/filter for Patina members, but we can also trivially add support for universities with college emails. This hasn't actually been implemented into the core logic yet, just the implementation.
> Implement user tags (DESC)

- js/src/app/dashboard/_components/DashboardLeaderboard/MyCurrentPoints.tsx
-Updated path for current points on mini leaderboard for the user
> Updated path for user current points

- js/src/components/ui/footer/Footer.tsx
A GitHub button next to Instagram was added to the footer. It takes you to the GitHub page of Codebloom.
> Added a github button in the footer

- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
Added the ability to filter based off Patina users on the fetch users from leaderboard route
> Add patina filter to leaderboard users route

- js/src/components/ui/footer/Footer.module.css
- js/src/components/ui/footer/Footer.tsx
-Before the logo on the footer was designed as button. Now, it is simply an image.
> Fix footer logo

- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
I implemented search by name into the leaderboard user's route.
> Implement search by name into the leaderboard users route

- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/lib/api/queries/leaderboard/index.ts
Implemented seach by name for the leaderboard on the frontend
- Added a search box in the leaderboard
-  changed the leaderboard query
> Implement leaderboard search by name on the frontend

- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
Edited leaderboardSqlRepository to allow search by user's nickname as well
> Added search by nickname

- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/components/ui/dropdown/FilterDropdown.tsx
- js/src/components/ui/dropdown/FilterDropdownItem.tsx
- js/src/lib/api/queries/leaderboard/index.ts
used the filter components we made to filter the leaderboard for users that are in Patina.
> added filtering to the frontend

- js/src/app/leaderboard/_components/LeaderboardSkeleton.tsx
Updated the array in LeaderboardSkeleton.tsx to have 17 entries instead of 2
> changed array to have 17 entries instead of 2

- src/main/java/com/patina/codebloom/common/leetcode/models/LeetcodeQuestion.java
- src/test/java/com/patina/codebloom/LeetcodeApiHandlerTest.java
-Created tests for submission user, submission ID, POTD, submission user, question Slug.
> Tests for LeetcodeApiClient's logic such as user submission, POTD, etc

- js/src/app/dashboard/_components/RefreshSubmissions.tsx
- js/src/lib/hooks/useCountdown.ts
Refactored the countdown logic for the submission button to be a custom hook called useCountdown, which helps us remove unnecessary useEffects inside of components. Furthermore, we will re-use this hook for other things that may need countdown, such as starting a new leaderboard
> Custom hook useCountdown (DESC)

- src/main/java/com/patina/codebloom/api/admin/AdminController.java
Created an admin controller and set up some boilerplate without creating any routes inside yet
> Created an AdminController and setup some boilerplate

- js/package.json
- js/pnpm-lock.yaml
Update Mantine packages 7.15.2 -> 7.17.3
> Update Mantine (DESC)

- js/src/app/dashboard/_components/DashboardLeaderboard/DashboardLeaderboard.tsx
- js/src/app/dashboard/_components/RecentSubmissions/RecentSubmissions.tsx
- js/src/components/ui/banner/Banner.tsx
Changed banner + dashboard to look better on mobile devices
> Added banner + dashboard ui enhancements

- src/main/java/com/patina/codebloom/api/auth/security/CustomAuthenticationSuccessHandler.java
Fixed bug on incorrect Patina tags being applied.
I moved the if statement to add Patina tags inside the loop that checks whether the user is part of the Patina server.
> fixed bug on Incorrect Patina tags being applied

- docs/setup/local.md
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
Implemented get all leaderboards in LeaderboardSqlRepository
Added Method in LeaderboardRepository
Fixed where the backend link didn't work for local.md
> Get all leaderboards to the LeaderboardRepository + fixed set up link for futhermore in local.md

- js/src/app/_component/AboutUs.tsx
- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
Added view full leaderboard button on the landing page for mobile and desktop users
> Added view full leaderboard button on the landing page for mobile and desktop users

- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
-Created interface that added all users to leaderboard and added metadata row.
> Added all users to leaderboardRepo

- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
-ensures all rows for adding users to the leaderboard are done in one go
> Batched users for addAllUsersToLeaderboard

- README.md
added my name
removed michaels
> author changes

- src/main/java/com/patina/codebloom/api/admin/AdminController.java
-Made in-function comments in AdminController as one line.
> Made comments in AdminController as one line

- src/main/java/com/patina/codebloom/api/admin/AdminController.java
- src/main/java/com/patina/codebloom/api/admin/body/UpdateAdminBody.java
-Added route, getters, and setters to toggle admin status if the user exists
> Toggle admin status

- js/src/lib/api/queries/auth/index.ts
- js/src/lib/api/types/user.ts
exposed isAdmin variable that checks if the user and session exist, then check if the user admin is true
> Create a new admin auth query

- js/src/app/admin/_components/admin.tsx
- js/src/app/admin/admin.page.tsx
added header and footer to admin page in admin.page.tsx
run the admin query and added react query stuff
redirect if not admin
> created an admin page

- js/src/components/ui/admin-button/AdminButton.tsx
- js/src/components/ui/footer/Footer.tsx
- js/src/lib/router.tsx
pointed /admin route to the AdminPage in router
Used admin query to show an admin button in the footer and connecting it to the admin page if isadmin is true
> Used the admin query to show an admin button in the footer + Point /admin route to the AdminPage in the router file

- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
Added leaderboard route to get shallow leaderboard meta data for all users
> Added leaderboard route to get leaderboard meta data

- js/src/app/_component/skeletons/MiniLeaderboardMobileSkeleton.tsx
- js/src/app/_component/skeletons/MiniLeaderboardSkeleton.tsx
- js/src/app/leaderboard/_components/LeaderboardSkeleton.tsx
- js/src/app/user/[userId]/_components/UserSubmissions/UserSubmissionsSkeleton.tsx
Updated the user profile page skeleton, Updated the landing page skeleton, and Updated the leaderboard skeleton
> Updated skeletons for multiple pages

- js/src/app/user/[userId]/UserProfile.page.tsx
I fixed the button `Go to dashboard` on the user profile page by looking at the submission details page and changing it to go back
> Fix the button `Go to dashboard` that's on the user profile page

- js/src/app/_component/OurFeatures.tsx
-Updated the time the POTD refreshes on the card on the Home Page.
> Updated the time the POTD refreshes on the card.

- js/src/lib/api/queries/leaderboard/index.ts
- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
-Added a fetchAllLeaderboardsMetadata to create Get Method to pull the data
-Added useAllLeaderboardsMetadataQuery function to create the query
> Created react hook query to fetch all leaderboard metadata

- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
- js/src/lib/types/FilterMetaData.ts
Changed the URL if the patina filter to be true by keeping the patina query
Updated it on both Mini leaderboards on mobile and desktop
> Load the leaderboard page with the patina query if patina is toggled on in the landing page

- js/src/app/admin/_components/AdminIndex.tsx
- js/src/app/admin/_components/NewLeaderboardForm.tsx
- js/src/lib/types/FilterMetaData.ts
Created a modal to create a new leaderboard with nothing in it yet
The component will import a modal that is invisible by default, and then a button that will toggle it on and off.
> Create the modal to create a new leaderboard

- src/main/java/com/patina/codebloom/api/user/UserController.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
-Overloaded getAllUsers() function add pagination to it
-Ensures other functions utilizing getAllUsers() does not break
> Added user controller to add pagination for getAllUsers controller.

- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- Added pagination to LeaderboardController
- Added function to count number of leaderboard
> Added pagination for Leaderboard Controller

- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/app/leaderboard/_components/LeaderboardMetadata/LeaderboardMetadata.tsx
- js/src/lib/hooks/useCountdown.ts
- Fixed a bug where negative values where allowed in useCountdown
- Cleaned up LeaderboardMetadata skeleton
- Refactored Tailwind classes into Mantine props
> Add logic to show timer to LeaderboardMetadata

- js/src/app/admin/_components/UserAdminList.tsx
- src/main/java/com/patina/codebloom/api/user/UserController.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
The problem was that the user count would always return the maximum amount of users, but we have search queries which can modify the amount of available pages.
> Fixed a bug where the total page count of the fetchAllUsers route was larger than it actually was

- src/main/java/com/patina/codebloom/common/schools/SchoolEnum.java
- src/main/java/com/patina/codebloom/common/schools/SupportedSchools.java
-Added the School Enum
- Added the SupportedSchools Class with getter
> Create an object for supported emails

- src/main/java/com/patina/codebloom/api/auth/AuthController.java
- src/main/java/com/patina/codebloom/api/auth/body/EmailBody.java
- Added /api/auth/school/validate POST Method
- Created EmailBody
> Create a new route to handle the logic of “verification”

- Makefile
- docs/backend/auth.md
-fixed bugs in the makefile
-fixed links in auth.md
> Fix the bugs in the Makefile

- Makefile
> Makefile error changes

- src/main/java/com/patina/codebloom/api/auth/AuthController.java
- src/main/java/com/patina/codebloom/common/schools/magic/MagicLink.java
-Created MagicLink Object
-Added new logic to check the school emails using magic link
> Pt 2 of setting up routes to validate schools

- Makefile
- js/package.json
- js/pnpm-lock.yaml
- js/src/app/admin/_components/AdminIndex.tsx
- js/src/app/admin/_components/announcements/NewAnnouncementModal.tsx
- js/src/components/ui/banner/Banner.tsx
- js/src/components/ui/banner/BannerParent.tsx
- js/src/lib/api/queries/admin/index.ts
- js/src/lib/api/queries/announcement/index.ts
- js/src/lib/api/schema/admin/index.ts
- js/src/lib/api/types/announcement.ts
- js/src/main.tsx
- src/main/java/com/patina/codebloom/api/admin/AdminController.java
- Implemented the ability to load announcements on the frontend and show them if valid
- Disallow announcements to have times set in the past
- Implement the ability to create a new announcement as an admin via the admin dashboard
> Announcements (Frontend)

- src/test/java/com/patina/codebloom/db/session/SessionRepositoryTest.java
Created a test file for SessionRepository
> SessionRepositoryTest

- js/src/app/settings/Settings.page.tsx
- js/src/app/settings/_components/SchoolEmailModal.tsx
- js/src/lib/api/queries/auth/school/index.ts
- js/src/lib/api/schema/school/index.ts
- js/src/lib/hooks/useBackendCallbackParams.ts
Added a zod schema to validate email being verified. Then created mutation to authenticate valid supported emails
> Verify School Modal

- pom.xml
-made changes to pom.xml inorder to stop sourcemaps to Sentry
> Stop uploading Java source maps to Sentry

- src/main/java/com/patina/codebloom/api/auth/AuthController.java
- src/main/java/com/patina/codebloom/common/db/models/user/PrivateUser.java
- src/main/java/com/patina/codebloom/common/db/models/user/User.java
- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
- src/main/java/com/patina/codebloom/common/security/AuthenticationObject.java
- src/main/java/com/patina/codebloom/common/security/Protector.java
- src/test/java/com/patina/codebloom/config/TestProtector.java
-Stopped showing school email when userprofile end point
Showed when school email when validate
> Strip school email from showing up automatically in certain endpoints

- js/src/app/leaderboard/[leaderboardId]/_components/LeaderboardWithId.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/components/ui/LeaderboardCard.tsx
- js/src/components/ui/dropdown/FilterDropdownItem.tsx
- js/src/lib/api/common/page.ts
- js/src/lib/api/queries/leaderboard/index.ts
- js/src/lib/helper/ordinal.ts
- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/helper/NamedPreparedStatement.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/options/LeaderboardFilterOptions.java
- src/main/java/com/patina/codebloom/common/page/Indexed.java
- src/test/java/com/patina/codebloom/db/leaderboard/LeaderboardRepositoryTest.java
Video showcasing new global leaderboard index
- Current + previous leaderboard
- Generate global indexes & filtered indexes
- Search does not affect indexes
https://github.com/user-attachments/assets/8fbbb7af-be5c-46f1-bc86-d64dd1c1f4a5
<p align="center">Data is a copy of production database, with sensitive information scrubbed away</p>
> Create global leaderboard index

- infra/Dockerfile
ErrorReporter won't be triggered without it.
> Update Dockerfile to set Spring profile in image

- js/package.json
- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
Leaderboard card fixed in desktop & mobile now that type errors are being thrown properly in CI
> Update typecheck command to run tsc properly + frontend fixes

- .github/workflows/ci-cd.yml
- Makefile
- docs/db/migrations.md
Delete the entire CI database and repopulate making sure we do this after all the other setup processes and finished, but beofre the backend tests begin.
> Added script to 'clean' CI database and then repopulate with migration

- .github/workflows/ci-cd.yml
Instead of the mocked data as well
> Changed to only use the migration file

- db/migration/V34__Add_GWC_to_tags_table.SQL
- db/repeated/R__Mock_v8.SQL
- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/models/usertag/Tag.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/options/LeaderboardFilterOptions.java
- Added  gwc to Tags
- Added db migration to include tags
- Added Filtering logic for gwc on the backend by editing the controller, sql 
- created a repeated db migration for a user with gwc tag
-
> Added Gwc Tag on the Backend

- js/src/app/user/[userId]/UserProfile.page.tsx
> fixed mobile responsiveness

- src/main/java/com/patina/codebloom/common/db/repos/user/UserSqlRepository.java
removed line that was causing error on schoolEmail and added COALESCE
> removed line that caused an error for school email

- Justfile
- email.sh
- email/email.md
- email/emails/template.tsx
- email/package.json
- email/pnpm-lock.yaml
- email/tsconfig.json
- Added script to send HTML output file to src/main/resources. 
- Added justfile comments for clarity and documentation for the react email
Running `just email-gen` sends the HTML output to src/main/resources/static
> Initialized React email starter project.

- js/src/lib/api/queries/leaderboard/index.ts
- js/src/lib/api/queries/user/index.ts
- js/src/lib/hooks/usePagination.ts
Leaderboard
https://github.com/user-attachments/assets/a45c28cc-fc20-49ef-b7b7-cbc50381653c
Leaderboard with ID
https://github.com/user-attachments/assets/b15a9b22-ff1d-4cd4-bcda-3e6bf97cc148
User admin list and all leaderboard list
https://github.com/user-attachments/assets/9a36f047-f764-4927-be89-b3c290afd666
> Added pagination logic to a helper hook for leaderboard functions

- js/src/lib/api/queries/user/index.ts
https://github.com/user-attachments/assets/c71317e0-3c61-4550-968c-5b1665f8f940
> Added overlay when changing submission pages

- .github/workflows/slash.yml
Must be merged into main before it can even be tested, according to [this](https://github.com/orgs/community/discussions/59389#discussion-5342063)
> Add slash command dispatch

- src/main/java/com/patina/codebloom/api/leaderboard/LeaderboardController.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardRepository.java
- src/main/java/com/patina/codebloom/common/db/repos/leaderboard/LeaderboardSqlRepository.java
- added new method for global rank and filter rank by id
- wrote the endpoint method that alllows ranking based off filters and non filters
**PATINA FILTER **
**WITHOUT PATINA FILTER**
> Write endpoint to get current place on leaderboard

- src/main/java/com/patina/codebloom/api/auth/AuthController.java
Redirected link:
Logger report:
> prevented error on existing school tag

- email/emails/school-email.tsx
> created school-email.tsx

- js/src/app/Root.page.tsx
- js/src/app/dashboard/Dashboard.page.tsx
- js/src/app/error/Error.page.tsx
- js/src/app/leaderboard/[leaderboardId]/_components/LeaderboardMetadataWithId.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/app/leaderboard/_components/LeaderboardMetadata/LeaderboardMetadata.tsx
- js/src/app/leaderboard/all/AllLeaderboards.page.tsx
- js/src/app/login/Login.page.tsx
- js/src/app/privacy/Policy.page.tsx
- js/src/app/settings/_components/SchoolVerifySettingsCard.tsx
- js/src/app/submission/[submissionId]/_components/SubmissionDetailsContent.tsx
1. Launch Page (https://codebloom.patinanetwork.org/): done in Root.page.tsx
2. Privacy Policy (https://codebloom.patinanetwork.org/privacy): done in Policy.page.tsx
3. Settings (https://codebloom.patinanetwork.org/settings): done in SchoolVerifySettingsCard.tsx
4. Log In (https://codebloom.patinanetwork.org/login): done in Login.page.tsx
5. Main Dashboard (https://codebloom.patinanetwork.org/dashboard): done in Dashboard.page.tsx
6. Main Leaderboard (https://codebloom.patinanetwork.org/leaderboard): done in Leaderboard.tsx
7. User Profile (https://codebloom.patinanetwork.org/user/780642a9-75a3-46e6-bf04-42dde47160e6): done in UserProfileHeader.tsx
8. Each Question Submission (https://codebloom.patinanetwork.org/submission/bb5e551e-0151-43e1-9461-2ce661991e3a): done in …
> Added dynamic titles and descriptions for pages

- src/main/java/com/patina/codebloom/api/admin/helper/PatinaDiscordMessageHelper.java
- src/main/java/com/patina/codebloom/jda/client/JDAClient.java
- src/main/java/com/patina/codebloom/jda/client/options/EmbeddedImagesMessageOptions.java
- src/main/java/com/patina/codebloom/scheduled/discord/WeeklyLeaderboard.java
> Screenshots for Patina #leetcode message

- js/src/app/_component/MiniLeaderboard.tsx
- js/src/app/_component/MiniLeaderboardMobile.tsx
- js/src/app/embed/leaderboard/gwc/_components/GwcEmbedView.tsx
- js/src/app/leaderboard/[leaderboardId]/_components/LeaderboardWithId.tsx
- js/src/app/leaderboard/_components/Leaderboard.tsx
- js/src/components/ui/LeaderboardCard.tsx
- Added the mantine LoadingOverlay effect in all places where Leaderboard Card is used
- Below is an example when switiching between school tags
> Added overlay for leaderboard cards
